import json
import os
import argparse
from typing import List, Dict, Any

from lgp.env.alfred.segmentation_definitions import OBJECT_CLASSES

# A mapping from natural language actions to ALFRED's formal action names.
ACTION_MAP = {
    'pick up': 'PickupObject',
    'put': 'PutObject',
    'toggle on': 'ToggleObjectOn',
    'toggle off': 'ToggleObjectOff',
    'slice': 'SliceObject',
    'open': 'OpenObject',
    'close': 'CloseObject',
    'stop': 'Stop'
}
# Also include the formal names to handle cases where the input is already formatted.
ALFRED_ACTION_LIST = list(ACTION_MAP.values())


def process_task_filenames(input_file: str, output_file: str):
    """
    Reads a list of trajectory file paths and converts them into a JSON split file
    that ALFRED can use.
    """
    print(f"Processing task filenames from: {input_file}")
    data_list = []
    last_task = ''
    repeat_idx = 0
    try:
        with open(input_file, 'r', encoding='utf-8') as f:
            for line in f:
                line = line.strip()
                if not line:
                    continue
                
                # This part is brittle. It assumes a very specific path structure.
                # A more robust solution might use os.path to extract relevant parts.
                task = line.replace('/data/syshin/alfred_data_all/json_2.1.0/valid_seen/', '').replace('/traj_data.json', '')
                
                if last_task == task:
                    repeat_idx += 1
                else:
                    repeat_idx = 0
                
                data_list.append({'task': task, 'repeat_idx': repeat_idx})
                last_task = task

        final_data_dict = {'valid_seen': data_list}
        
        os.makedirs(os.path.dirname(output_file), exist_ok=True)
        with open(output_file, 'w', encoding='utf-8') as f:
            json.dump(final_data_dict, f, indent=2)
        print(f"Successfully created splits file: {output_file}")

    except FileNotFoundError:
        print(f"Error: Input file not found at {input_file}")
    except Exception as e:
        print(f"An error occurred during task filename processing: {e}")


def parse_raw_policies(input_file: str, output_file: str):
    """
    Parses a raw text file of policies generated by an LLM into a structured JSON file.
    """
    print(f"Parsing raw policies from: {input_file}")
    entire_policy_list = []
    current_policy = []
    try:
        with open(input_file, 'r', encoding='utf-8') as f:
            for line in f:
                line = line.strip()
                if not line:
                    continue

                if '(' in line and ')' in line:
                    # Extract content within parentheses
                    content = line[line.find('(') + 1:line.rfind(')')]
                    args = [arg.strip() for arg in content.split(',')]
                    
                    if not args or not args[0]:
                        continue

                    action = args[0]
                    if len(args) == 1:
                        policy_step = {'action': action, 'object': ''}
                    elif len(args) == 2:
                        policy_step = {'action': action, 'object': args[1]}
                    else: # Handles cases like put(obj, in, recep)
                        if 'put' in action.lower():
                            policy_step = {'action': action, 'object': args[2]}
                        else:
                            policy_step = {'action': action, 'object': args[1]}
                    current_policy.append(policy_step)
                
                # A line without parentheses is treated as a separator between policies
                elif len(current_policy) > 0:
                    entire_policy_list.append(current_policy)
                    current_policy = []
        
        # Add the last policy if the file doesn't end with a separator
        if len(current_policy) > 0:
            entire_policy_list.append(current_policy)

        # Convert to the required dictionary format {index: policy_list}
        policy_dict = {str(i): policy for i, policy in enumerate(entire_policy_list)}
        
        os.makedirs(os.path.dirname(output_file), exist_ok=True)
        with open(output_file, 'w', encoding='utf-8') as f:
            json.dump(policy_dict, f, indent=2)
        print(f"Successfully parsed raw policies to: {output_file}")

    except FileNotFoundError:
        print(f"Error: Input file not found at {input_file}")
    except Exception as e:
        print(f"An error occurred during raw policy parsing: {e}")


def find_best_object_match(object_str: str) -> str:
    """Finds the best matching ALFRED object class for a given string."""
    if not object_str:
        return ""
    
    # Normalize the input string
    normalized_obj_str = object_str.lower().replace(' ', '')
    
    # 1. Exact match (case-insensitive, space-insensitive)
    for o_class in OBJECT_CLASSES:
        if o_class.lower() == normalized_obj_str:
            return o_class
            
    # 2. Substring match
    for o_class in OBJECT_CLASSES:
        if o_class.lower() in normalized_obj_str or normalized_obj_str in o_class.lower():
            return o_class
            
    # 3. If no good match is found, return the original string for manual inspection.
    return object_str


def normalize_policies(input_file: str, output_file: str):
    """
    Normalizes action names and object names in a parsed policy JSON file to match
    ALFRED's internal vocabulary.
    """
    print(f"Normalizing policies from: {input_file}")
    try:
        with open(input_file, 'r', encoding='utf-8') as f:
            data = json.load(f)

        normalized_data = {}
        for task_id, policy in data.items():
            normalized_policy = []
            for step in policy:
                action = step.get('action', '').lower()
                obj = step.get('object', '')

                # Normalize action
                if action in ACTION_MAP:
                    normalized_action = ACTION_MAP[action]
                elif step.get('action') in ALFRED_ACTION_LIST:
                    normalized_action = step.get('action')
                else:
                    continue # Skip steps with unrecognized actions

                # Normalize object
                normalized_object = find_best_object_match(obj)
                
                normalized_policy.append({
                    'action': normalized_action,
                    'object': normalized_object
                })
            normalized_data[task_id] = normalized_policy
        
        os.makedirs(os.path.dirname(output_file), exist_ok=True)
        with open(output_file, 'w', encoding='utf-8') as f:
            json.dump(normalized_data, f, indent=2)
        print(f"Successfully normalized policies to: {output_file}")
        print(f"Original policy count: {len(data)}, Normalized policy count: {len(normalized_data)}")

    except FileNotFoundError:
        print(f"Error: Input file not found at {input_file}")
    except json.JSONDecodeError:
        print(f"Error: Could not decode JSON from {input_file}")
    except Exception as e:
        print(f"An error occurred during policy normalization: {e}")


def main():
    """Main function to run the data processing pipeline."""
    parser = argparse.ArgumentParser(description="Process raw LLM policy outputs into ALFRED-compatible JSON files.")
    parser.add_argument('--input-dir', type=str, required=True, help="Directory containing the raw .txt files from the LLM.")
    parser.add_argument('--output-dir', type=str, required=True, help="Directory to save the processed .json files.")
    parser.add_argument('--mode', type=str, default='experiment', help="An identifier for the experiment run.")
    parser.add_argument('--policy-file-num', type=int, default=0, help="The number prefix of the policy file to process.")
    
    args = parser.parse_args()

    # Define input paths
    filename_list_input = os.path.join(args.input_dir, f"file_name_decompose_{args.mode}.txt")
    raw_policy_input = os.path.join(args.input_dir, f"{args.policy_file_num}.policy_decompose_{args.mode}.txt")

    # Define output paths
    splits_output = os.path.join(args.output_dir, 'splits', f'decompose_{args.mode}.json')
    parsed_policy_output = os.path.join(args.output_dir, 'policy_data', f'decompose_{args.mode}.json')
    normalized_policy_output = os.path.join(args.output_dir, 'policy_data', f'decompose_{args.mode}_modify.json')

    # Run the pipeline
    # Step 1: Create ALFRED splits file (optional, if needed)
    # process_task_filenames(filename_list_input, splits_output)
    
    # Step 2: Parse raw text policies into structured JSON
    parse_raw_policies(raw_policy_input, parsed_policy_output)
    
    # Step 3: Normalize actions and objects to match ALFRED vocabulary
    normalize_policies(parsed_policy_output, normalized_policy_output)

if __name__ == "__main__":
    main()



